---
title: "Cronograma da Disciplina"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

Esta página contém um esboço dos tópicos, conteúdos e tarefas para o semestre. Este cronograma será atualizado conforme o semestre avança.

<!-- https://fontawesome.com/search?o=r&m=free -->

<!-- https://jpswalsh.github.io/academicons/ -->

<!-- [{{< fa file-pdf size=2xl >}}](/weeks/week-1.html#prepare){aria-label="Week 1 summary"}  |  [️](/slides/lec-1.html "Lecture slides"){aria-label="Lecture 1 slides"}  |       [{{< fa laptop-file size=2xl >}}](/ae/ae-0-movies.html "Application exercise"){aria-label="Application Exercise 0 instructions"} -->

<!-- {{< fa brands r-project size=2xl >}}  -  scripts -->

<!-- {{< fa file-powerpoint size=2xl >}}   -  slides -->

<!-- {{< fa laptop-file size=2xl >}}  -  estudo de caso -->

<!-- {{< fa file-pdf size=2xl >}}  -  artigo -->

<!-- {{< fa table size=2xl >}}  -  tabelas estatisticas -->

<!-- {{< fa file-lines size=2xl >}}  -  exercicios -->

<!-- {{< fa folder size=2xl >}}  -  material complementar -->

<!-- {{< fa list-check size=2xl >}}  -  projeto -->

::: column-screen-inset-right
| Semana | Data | Tópico | Artigo | Slides | EC | LE | Script | MC | Projeto |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| [6](programacao/semana-6.html) | Ter, 11/11 | Outras Distribuições Contínuas |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/outras_distr_continuas/outras_dist_continuas.html#/title-slide "Outras Distribuições Contínuas"){aria-label="Outras Distribuições Contínuas"} |  |  |  |  |  |
|  | Qui, 13/11 | Outras Distribuições Contínuas |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/outras_distr_continuas/outras_dist_continuas.html#/title-slide "Outras Distribuições Contínuas"){aria-label="Outras Distribuições Contínuas"} |  |  |  |  |  |
| [7](programacao/semana-7.html) | Ter, 18/11 | Não haverá aula |  |  |  |[{{< fa file-lines size=2xl >}}](/exercicios/lista01.html "Lista de Exercícios 01"){aria-label="Lista de Exercícios 01"}  |  |  |  |
|  | Qui, 20/11 | Feriado: não haverá aula |  |  |  |  |  |  |  |
| [8](programacao/semana-8.html) | Ter, 25/11 | Outras Distribuições Contínuas |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/outras_distr_continuas/outras_dist_continuas.html#/distribuição-weibull "Outras Distribuições Contínuas"){aria-label="Outras Distribuições Contínuas"} |  |  |  |  |  |
|  | Qui, 27/11 | Transformação de Variáveis Aleatórias |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/transformacoes/transformacoes.html#/title-slide "Transformação de Variáveis Aleatórias"){aria-label="Transformação de Variáveis Aleatórias"} |  |  |  |  |  |
| [9](programacao/semana-9.html) | Ter, 02/12 |  Transformação de Variáveis Aleatórias |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/transformacoes/transformacoes.html#/função-de-variável-aleatória-caso-contínuo "Transformação de Variáveis Aleatórias"){aria-label="Transformação de Variáveis Aleatórias"} |  |[{{< fa file-lines size=2xl >}}](/exercicios/lista02.html "Lista de Exercícios 02"){aria-label="Lista de Exercícios 02"}  |  |  |  |
|  | Qui, 04/12 |  Transformação de Variáveis Aleatórias |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/transformacoes/transformacoes.html#/função-de-variável-aleatória-caso-contínuo "Transformação de Variáveis Aleatórias"){aria-label="Transformação de Variáveis Aleatórias"} |  |  |  |  |  |
| [10](programacao/semana-10.html) | Ter, 09/12 | Função Geradora de Momentos |  |[{{< fa file-powerpoint size=2xl >}}](/aulas/func_geradora_momentos/func_gera_momentos.html#/title-slide "Função Geradora de Momentos"){aria-label="Função Geradora de Momentos"}  |  |  |  |  |  |
|  | Qui, 11/12 | Função Geradora de Momentos |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/func_geradora_momentos/func_gera_momentos.html#/função-geradora-de-momentos-9 "Função Geradora de Momentos"){aria-label="Função Geradora de Momentos"} |  |[{{< fa file-lines size=2xl >}}](/exercicios/lista03.html "Lista de Exercícios 03"){aria-label="Lista de Exercícios 03"}  |  |  |  |
| [11](programacao/semana-11.html) | Ter, 16/12 | Função Geradora de Momentos |  |[{{< fa file-powerpoint size=2xl >}}](/aulas/func_geradora_momentos/func_gera_momentos.html#/função-geradora-de-momentos-32 "Função Geradora de Momentos"){aria-label="Função Geradora de Momentos"}  |  |  |  |  |  |
|  | Qui, 18/12 | Função Geradora de Momentos |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/func_geradora_momentos/func_gera_momentos.html#/função-característica-2 "Função Geradora de Momentos"){aria-label="Função Geradora de Momentos"} |  |[{{< fa file-lines size=2xl >}}](/exercicios/lista04.html "Lista de Exercícios 04"){aria-label="Lista de Exercícios 04"}  |  |  |  |
|  |  | **22/12 a 17/01  -  Recesso Acadêmico** |  |  |  |  |  |  |  |
| [12](programacao/semana-12.html) | Ter, 20/01 | Integrais Duplas e Triplas |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/integrais_dup_trip/integrais_dup_trip.html#/title-slide "Integrais Duplas e Triplas"){aria-label="Integrais Duplas e Triplas"} |  |  |  |  |  |
|  | Qui, 22/01 |  Integrais Duplas e Triplas |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/integrais_dup_trip/integrais_dup_trip.html#/title-slide "Integrais Duplas e Triplas"){aria-label="Integrais Duplas e Triplas"} |  |  |  |  |  |
| [13](programacao/semana-13.html) | Ter, 27/01 | Tira dúvidas |  |  |  |  |  |  |  |
|  | Qui, 29/01 | Primeira Prova |  |  |  |  |  |  |  |
<!-- | [14](programacao/semana-14.html) | Ter, 05/08 | Reconhecimento de Padrões |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/Reconhecimento_padroes/padroes.html#/método-mean-shift "Método Mean Shift"){aria-label="Método Mean Shift"} |  |  |  |  |  | -->
<!-- |  | Qui, 07/08 | Reconhecendo padrões usando a base de dados Space Titanic |  |  |  |  | [{{< fa brands r-project size=2xl >}}](analise_dados/space_titanic_cluster.html "Script análise de dados"){aria-label="Script análise de dados"} |  | [{{< fa list-check size=2xl >}}](/projeto/projeto_avaliativo.html#fase-4-reconhecimento-de-padrões-e-segmentação-de-clientes "Projeto: fase 4"){aria-label="Projeto: fase 4"} | -->
<!-- | [15](programacao/semana-15.html) | Ter, 12/08 | Regras de Associação |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/Regras_associacao/associacao.html "Regras de associação"){aria-label="Regras de associação"} |  |  |  |  |  | -->
<!-- |  | Qui, 14/08 | Regras de Associação |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/Regras_associacao/associacao.html#/algoritmo-apriori "Algoritmo Apriori"){aria-label="Algoritmo Apriori"} |  |  |  |  |  | -->
<!-- | [16](programacao/semana-16.html) | Ter, 19/08 | Regras de Associação |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/Regras_associacao/associacao.html#/exemplo-de-regras-de-associação-com-a-base-de-dados-groceries "Exemplo Groceries"){aria-label="Exemplo Groceries"} |  |  | [{{< fa brands r-project size=2xl >}}](analise_dados/space_titanic_regras.html "Script análise de dados"){aria-label="Script análise de dados"} |  | [{{< fa list-check size=2xl >}}](/projeto/projeto_avaliativo.html#fase-5-construção-de-um-sistema-de-recomendação "Projeto: fase 5"){aria-label="Projeto: fase 5"} | -->

<!-- |                           | Qui, 14/08 | Regras de Associação | | [{{< fa file-powerpoint size=2xl >}}](/aulas/Regras_associacao/associacao.html#/algoritmo-apriori "Algoritmo Apriori"){aria-label="Algoritmo Apriori"} | | || | | -->
:::

```{r echo = FALSE}
knitr::knit_exit()
```


