---
title: "Lista de exercícios 01: Revisão de Probabilidade I"
format:
  html:
    number-sections: true
    toc: true
    toc-depth: 2
  pdf:
    number-sections: true
    toc: false
    toc-depth: 2
---

<p align="center" style="font-size: 40px"> 
`Data de entrega: 25 de novembro de 2025`
</p>


---

1) A demanda diária de **arroz** em um supermercado (em *centenas de quilos*) é uma variável aleatória contínua $X$ com função densidade de probabilidade

$$
f_X(x)=
\begin{cases}
\dfrac{2x}{3}, & 0<x<1,\\\\
1-\dfrac{x}{3}, & 1<x<3,\\\\
0, & \text{caso contrário.}
\end{cases}
$$

Considere as questões a seguir.

a) Mostre que $f_x(x)$ é uma função densidade de probabilidade para a demanda de arroz.

b) Qual a probabilidade de, em um dia escolhido ao acaso, se vender mais que 150 kg de arroz?

c) Em 30 dias, quanto o gerente do supermercado espera vender?

d) Determine a função de distribuição acumulada de $X$.

e) Qual é a quantidade de arroz que deve ser deixada à disposição do público diariamente para que não falte arroz com $95\%$ de probabilidade?

f) Qual é a demanda mediana de arroz?

g) E a demanda modal?

---

2) A temperatura $T$ de destilação do petróleo é crucial na determinação da qualidade final do produto. Suponha que $T$ seja considerada uma v.a. com distribuição uniforme no intervalo de 150 a 300. Suponha que o custo para produzir um galão de petróleo seja $C_1 u.m.$. Se o óleo é destilado a uma temperatura inferior a 200, o produto obtido é vendido a $C_2 u.m.$;  se a temperatura for superior a 200, o produto é vendido a $C_3 u.m.$.

a) Fazer o gráfico da f.d.p de $T$.  

b) Qual o lucro esperado por galão?

---

3. O diâmetro $X$ de rolamentos de esferas fabricados por certa fábrica tem distribuição $N(0,6140;\ (0,0025)^2)$. O lucro $T$ de cada esfera depende de seu diâmetro e

- $T=0,10$ se a esfera é boa $(0,6100 < X < 0,6180)$
- $T=0,05$ se a esfera é recuperável $(0,6080 < X < 0,6100)$ ou $(0,6180 < X < 0,6200)$
- $T=-0,10$ se a esfera é defeituosa $(X < 0,6080 \text{ ou } X > 0,6200)$.

**Determine $E[T]$.**

---

4. Em uma determinada localidade, a renda em **1000 u.m.** é uma v.a. $X$ com função densidade de probabilidade:
$$
f_X(x)=
\begin{cases}
\dfrac{x+1}{10}, & 0<x<2,\\[6pt]
\dfrac{18-3x}{40}, & 2<x<6,\\[6pt]
0, & \text{c.c.}
\end{cases}
$$

a) Mostre que $f_X(x)$ é uma função densidade de probabilidade para $X$.

b) Determine a função de distribuição acumulada de $X$.

c) Escolhida uma pessoa ao acaso, qual é a probabilidade de sua renda exceder **3.000 u.m.**?

d) Determine a **renda média** nessa localidade.

e) Determine a **renda mediana** nessa localidade.

f) Determine o **1º** e o **3º** quartis da variável renda.


--- 

5. As notas de **Probabilidade** dos alunos de determinada universidade seguem a **distribuição normal**, com média $6{,}4$ e desvio-padrão $0{,}8$. O professor atribui graus **A**, **B** e **C**, da seguinte forma:

- **C**, para notas inferiores a $5$
- **B**, para notas entre $5$ e $7{,}5$
- **A**, para notas superiores a $7{,}5$

a) Qual a probabilidade de um aluno receber conceito **A**?  
b) Qual a probabilidade de um aluno receber conceito **B**?  
c) Qual a probabilidade de um aluno receber conceito **C**?  
d) Se a turma tem 80 alunos, quantos devem receber cada conceito, em média?

---

6. Suponha que o número de milhas que um carro percorre antes que sua bateria sofra desgaste tenha distribuição Exponencial com média de 10.000 milhas. Se uma pessoa deseja fazer uma viagem de 5.000 milhas com uma bateria já usada por 8.000 milhas, qual é a probabilidade de terminar a viagem sem ter que trocar a bateria?

---

7. O tempo de vida dos pneus de certo fabricante tem distribuição Exponencial, com duração média de 50.000 km.

a) Determine a probabilidade de que um pneu deste fabricante dure mais que 50.000 km.  

b) Qual é o tempo de vida que o fabricante deve garantir de forma que, no máximo, 1% dos compradores utilizem a garantia?  

c) Você acha que a distribuição exponencial é adequada a esta situação? Justifique.

---

8. O número de clientes chegando a um certo estabelecimento comercial segue a distribuição de Poisson. Em média, chegam 10 clientes a cada hora.

a) Determine a probabilidade de que o tempo até a chegada do primeiro cliente exceda 5 minutos.  

b) Determine a probabilidade de que o tempo entre chegadas sucessivas de dois clientes quaisquer exceda 5 minutos.  

c) Determine a probabilidade de que o tempo até a chegada do quinto cliente exceda 30 minutos.  

d) Determine a probabilidade de que chegue algum cliente nos próximos 30 minutos, uma vez que nenhum cliente chegou na última hora.  

e) Determine o tempo médio entre chegadas sucessivas. Este é um bom valor preditivo?  

f) Determine o tempo mediano entre chegadas sucessivas.  

g) Determine o tempo médio até a chegada do quinto cliente. Este é um bom valor preditivo?

---

9. Suponha-se que um fusível tenha uma duração de vida $X$, a qual pode ser considerada uma variável aleatória contínua com distribuição Exponencial. Existem dois processos pelos quais o fusível pode ser fabricado. O processo I apresenta uma duração de vida esperada de 100 horas, enquanto o processo II apresenta uma duração de vida esperada de 150 horas. Suponha-se que o processo II seja duas vezes mais custoso que o processo I, que custa 3,00 u.m. por fusível. Admita-se, além disso, que se um fusível durar menos que 200 horas, uma multa de 20 u.m. seja lançada sobre o fabricante. Qual processo deve ser empregado de forma a se minimizar o custo esperado?

---

<!-- 10. Seja $X$ uma v.a. com distribuição Qui-quadrado com: -->

<!-- a) 10 graus de liberdade. Determine, de forma exata, $P(X>9)$.   -->

<!-- b) 120 graus de liberdade. Determine uma aproximação para $P(X>140)$. -->

<!-- --- -->

<!-- 11.Seja $X$ uma variável aleatória com distribuição $Beta(3,2)$. -->

<!-- a) Determine a função de distribuição acumulada de $X$.   -->

<!-- b) Determine $P(X > 1/2)$. -->

<!-- --- -->

<!-- 12.Seja $X$ uma variável aleatória com distribuição $Weibull(3,0.005)$. -->

<!-- a) Determine os quartis de $X$.   -->

<!-- b) Suponha que $X$ represente o tempo de vida (em h) de um componente. Determine a confiabilidade desse componente para 50 horas.   -->

<!-- c) Determine a probabilidade de que o componente dure mais que 250 horas, uma vez que já esteja em funcionamento por 200 horas.   -->

<!-- d) Determine a duração esperada do componente. O valor esperado é um bom preditor para essa variável aleatória? Use os seguintes fatos: $\Gamma(1/3)=2{,}678939$ e $\Gamma(2/3)=1{,}354118$. -->

<!-- --- -->

10.Mostre que se $X$ é uma variável aleatória contínua, com distribuição $Uniforme(a,b)$, então:

$$E[X] = \frac{a+b}{2} \quad \text{e} \quad V[X] = \frac{(b-a)^2}{12}.$$

---

11.Mostre que se $X \sim Exponencial(\lambda)$, então:

$$E[X] = \frac{1}{\lambda} \quad \text{e} \quad V[X] = \frac{1}{\lambda^2}.$$

---

12.Mostre que se $X \sim Exponencial(\lambda)$, então $P(X > t + s \mid X > t) = P(X > s)$, ou seja, a distribuição Exponencial goza da propriedade de *"Falta de Memória"*.

---

<!-- 16.Mostre que se $X \sim Gama(\alpha, \lambda)$, então: -->

<!-- $$E[X] = \frac{\alpha}{\lambda} \quad \text{e} \quad V[X] = \frac{\alpha}{\lambda^2}.$$ -->

<!-- --- -->

<!-- 17.Mostre que se $X \sim Weibull(\alpha, \lambda)$, então: -->

<!-- $$E[X] = \frac{1}{\lambda} \, \Gamma\!\left(1+\frac{1}{\alpha}\right)  -->
<!-- \quad \text{e} \quad  -->
<!-- V[X] = \frac{1}{\lambda^2} \left[\Gamma\!\left(1+\frac{2}{\alpha}\right) - \Gamma^2\!\left(1+\frac{1}{\alpha}\right)\right].$$ -->

13. Uma fábrica produz 10 recipientes de vidro por dia. Deve-se supor que exista uma probabilidade constante $p = 0,1$ de produzir um recipiente defeituoso. Antes que esses recipientes sejam estocados, eles são inspecionados e os defeituosos são separados. Admita que exista uma probabilidade constante $r = 0,1$ de que um recipiente defeituoso seja mal classificado. Faça $X$ igual ao número de recipientes classificados como defeituosos ao fim de um dia de produção. (Admita que todos os recipientes fabricados em um dia sejam inspecionados naquele dia.)

a) Calcule $P(X = 3)$ e $P(X > 3)$.

b) Obtenha a expressão de $P(X = k)$.

---

14. O número de navios petroleiros, digamos $N$, que chegam a determinada refinaria, cada dia, tem distribuição de Poisson, com parâmetro $\lambda = 2$. As atuais instalações do porto podem atender a três petroleiros por dia. Se mais de três petroleiros aportarem por dia, os excedentes a três deverão seguir para outro porto.

a)Em um dia, qual é a probabilidade de se ter de mandar petroleiros para outro porto?

b)De quanto deverão as atuais instalações ser aumentadas para permitir manobrar todos os petroleiros, em aproximadamente $90\%$ dos dias?

c)Qual é o número esperado de petroleiros a chegarem por dia?

d)Qual é o número mais provável de petroleiros a chegarem por dia?

e)Qual é o número esperado de petroleiros a serem atendidos diariamente?

f)Qual é o número esperado de petroleiros que voltarão a outros portos diariamente?

---

15. A probabilidade de um bem-sucedido lançamento de foguete é igual a 0,8. Suponha que tentativas de lançamento sejam feitas até que tenham ocorrido 3 lançamentos bem-sucedidos. Qual é a probabilidade de que exatamente 6 tentativas sejam necessárias? Qual é a probabilidade de que menos de 6 tentativas sejam necessárias?

---

16. Na situação descrita no Probl. 15, suponha que as tentativas de lançamento sejam feitas até que três lançamentos bem-sucedidos, consecutivos, ocorram. Responda às questões que surgiram no problema anterior, neste caso.

---

17.Considere novamente a situação descrita no Probl. 15. Suponha que cada tentativa de lançamento custe $R\$ 25.000,00$. Além disso, um lançamento falho acarrete um custo adicional de $R\$ 5.000,00$. Calcule o custo esperado, para a situação apresentada.